# Theme
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

# Site Settings
title: しまねOSS協議会 OS4
tagline: しまねOSS協議会
email: info@shimane-oss.org
description: >
  しまねOSS協議会（Open Source Software Society Shimane : OS4）は、
  島根県内におけるOSS（オープン・ソース・ソフトウェア）に関わる
  企業、技術者、研究者、そしてユーザによる組織です。
baseurl: ""
url: "www.shimane-oss.org"
permalink: pretty
#favicon: /path/to/favicon.png
hide_share_buttons: true

paginate: 5
paginate_path: "/events/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
    values:
      lang: ja_JP
      show_sidebar: true
      hero_height: is-small
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      image: /images/ogp.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      hero_darken: false
      author: "しまねOSS協議会"

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu
